# Generated by Django 4.1.3 on 2022-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardgame_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardgame",
            name="summary",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
