# Generated by Django 4.1.3 on 2022-12-09 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boardgame_site", "0005_alter_lending_lender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="lender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
