# Generated by Django 4.1.3 on 2022-12-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardgame_site", "0006_alter_lending_lender"),
    ]

    operations = [
        migrations.AddField(
            model_name="lending",
            name="received_game_date",
            field=models.DateTimeField(null=True),
        ),
    ]
