# Generated by Django 4.1.3 on 2022-12-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardgame_site", "0007_lending_received_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="available_to_lend",
            field=models.BooleanField(null=True),
        ),
    ]
